### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by weiwsmiling** [nerettilab/RepEnrich#1]
Dear Sir:
I am trying to use RepEnrich. When I run the setup, there is an error happened.Hope can get your help.Thanks!

This is my command:
RepEnrich_setup.py hg19_repeatmasker.txt /home/wgf/Project/hg19/Sequence/BowtieIndex/genome.fa setup_folder_hg19

And the error report is:
raceback (most recent call last):
  File "RepEnrich_setup.py", line 160, in <module>
    rend = min(rep_end_current[i] + flankingl, lgenome[chr]-1)
KeyError: 'chr6_ssto_hap7'

Wei

**Comment by scriscio** [comment]
Hi Wei,

  I believe this issue has to do with how you made the reference assembly. I think what is happening is that your annotation file contains annotation for repeat elements on chromosomes "chr6_ssto_hap7", but it is not included in the assembly genome.fa.  
   To verify this is the cause try and use grep to check if what I said is true.
`grep "chr6_ssto_hap7" hg19_repeatmasker.txt`
... should yield positive matches. However, 
`grep "chr6_ssto_hap7" genome.fa`
... should not yield matches.
   To fix this issue you could either add the missing chromosomes to the genome.fa reference assembly or remove these additional chromosome repeat annotation from your hg19_repeatmasker.txt.  The actual assembly includes multiple unassigned contigs and alternate haplotypes, which are most likely in your annotation but not in your reference sequence.
`grep -v "chr6_ssto_hap7" hg19_repeatmasker.txt > hg19_repeatmasker.txt.fix`
   Could be used to remove an unwanted chromosome.  There are most likely multiple of these that will be problematic. See here for the full list of chromosome names in hg19.
https://genome.ucsc.edu/cgi-bin/hgTracks?hgsid=12832096&chromInfoPage=

**Comment by weiwsmiling** [comment]
Thanks!
