### ISSUE TITLE
Using Bowtie2/TopHat with RepEnrich

### ISSUE THREAD

**Issue by sudhirthakurela** [nerettilab/RepEnrich#20]
Hi,

I would like to use RepEnrich but with either preferentially with TopHat or with Bowtie2. As the options of -m and --max options are no more valid in Bowtie2, do you have any suggestions/recommendation to run RepEnrich with Tophat or Bowtie2?

ST

**Comment by scriscio** [comment]
Checkout https://github.com/nskvir/RepEnrich2
