### ISSUE TITLE
Bus error (core dumped) - ERROR

### ISSUE THREAD

**Issue by vasilislenis** [nerettilab/RepEnrich#21]
Hi there,

First of all, I would like to wish you a happy new year.

My name is Vasilis and I am working as a postdoc at Plymouth University. I am trying to run RepEnrich on some samples that I have but I faced the following problem:

Following the tutorial (which is great by the way) I managed to complete the 3rd step.
When I am trying to run the RepEnrich for the fourth step I receive the following error:

**Bus error (core dumped)**

The command that I am submitting is the following:

**python RepEnrich.py ../trans_elements/hg19_repeats.bed /data/vlenis/Alzheimer_data/SRR1931812/ sample_SRR1931812 /data/vlenis/Alzheimer_data/setup_folder_hg19 /data/vlenis/Alzheimer_data/raw_data/SRR1931812_multimap.fastq /data/vlenis/Alzheimer_data/raw_data/SRR1931812_unique.bam --is_bed TRUE --cpus 16**

I have followed exactly the installation process that you describe in the tutorial and all the tools are exactly the same version that you said.

I would like Kindly to ask you for your lights.

Thank you in advance,
Vasilis.

**Comment by nskvir** [comment]
Figured I would copy the resolution communicated via email here in case anyone encounters this error in the future:

    Hi Nicolas,
    
    Thank you very much for your reply. 
    I believe that I have sorted it out. The problem was the NumPy. My disk was full and for some reason 
    NumPy was crashing the system.
    Now it seems that it is running.
    I’ll let you know how it goes.
    
    My apologies in advance in case that I will bother you again :)
    
    Thank you very much,
    Vasilis.
