### ISSUE TITLE
RepEnrich2_setup.py "Duplicate key error" 

### ISSUE THREAD

**Issue by PT0106** [nerettilab/RepEnrich#24]
Hi,

I'm trying to run the RepEnrich2_setup.py for the mm10 genome using a repeat file generated as per protocol for LINE elements from the UCSC genome browser table.  However, I am getting a "ValueError: Duplicate key''" when I run the python code.  I tried filtering the repeatmasker file for unique lines but outputs the same number of lines.  Would you be able to provide me with some assistance? 

Thanks!

**Comment by nskvir** [comment]
Hi there,
Do you happen to know what line the error occurs on?  If you want, feel free to e-mail me the repeat file you generated (nicholas_skvir at brown.edu) and I can try to reproduce the error and get to the bottom of it when I have some time!

Best,
Nick
