### ISSUE TITLE
Failed early!

### ISSUE THREAD

**Issue by imtheman69** [nerettilab/RepEnrich#3]
Hi,
I'm keen to try RepEnrich - and I've failed early.
I keep getting the "File "RepEnrich_setup.py", line 38
    print "Error: Bowtie or BEDTools not loaded"
                                               ^
I am sure BEDTools and Bowtie are loaded.

Here is my command:
python RepEnrich_setup.py ./data/mm9_repeatmasker.txt mm9.fa ./data/setup_folder_mm9

Cheers in advance,
DD

**Comment by scriscio** [comment]
Hi,

   This error refers to bedtools or bowtie not being in the path, which the program requires. To verify this is true you could try the following commands in the command line:

bowtie --version
coverageBed -h

One of these should fail, which is why the exception is being raised.  To put bedtools and bowtie in the working path manual you can do:
PATH=$PATH:/path/to/my/program

and replacing /path/to/my/program to /path/to/bedtools You can check that they have been added by running:

echo $PATH
and the prior commands:
bowtie --version
coverageBed -h

-scriscio

**Comment by imtheman69** [comment]
Hi,
Thats weird. Both prog's are in the PATH (I am using a hi performance cluster).
However, I am using python apps/gcc/python/3.3.2 which I
guess isnt exactly BioPython.

$bowtie --version
bowtie version 1.0.0
64-bit
Built on headnode.ledaig.local
Wed Oct  9 16:46:10 BST 2013
Compiler: gcc version 4.1.2 20080704 (Red Hat 4.1.2-50)
Options: -O3 -m64  -Wl,--hash-style=both
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

$ coverageBed -h

Tool:    bedtools coverage (aka coverageBed)
Version: v2.20.1
Summary: Returns the depth and breadth of coverage of features from A
         on the intervals in B.

Usage:   bedtools coverage [OPTIONS] -a <bed/gff/vcf> -b <bed/gff/vcf>

Options:
        -abam   The A input file is in BAM format. Replaces -a.

```
    -s      Require same strandedness.  That is, only counts hits in A that
            overlap B on the _same_ strand.
            - By default, overlaps are counted without respect to strand.

    -S      Require different strandedness.  That is, only report hits in A
            that overlap B on the _opposite_ strand.
            - By default, overlaps are counted without respect to strand.

    -hist   Report a histogram of coverage for each feature in B
            as well as a summary histogram for _all_ features in B.

            Output (tab delimited) after each feature in B:
              1) depth
              2) # bases at depth
              3) size of B
              4) % of B at depth

    -d      Report the depth at each position in each B feature.
            Positions reported are one based.  Each position
            and depth follow the complete B feature.

    -counts Only report the count of overlaps, don't compute fraction, etc.

    -split  Treat "split" BAM or BED12 entries as distinct BED intervals.
            when computing coverage.
            For BAM files, this uses the CIGAR "N" and "D" operations
            to infer the blocks for computing coverage.
            For BED12 files, this uses the BlockCount, BlockStarts,
            and BlockEnds fields (i.e., columns 10,11,12).
```

Default Output:
         After each entry in B, reports:
           1) The number of features in A that overlapped the B interval.
           2) The number of bases in B that had non-zero coverage.
           3) The length of the entry in B.
           4) The fraction of bases in B that had non-zero coverage.

**Comment by scriscio** [comment]
Hi,

   I noticed that you are using python/3.3.2.  RepEnrich was written using python 2.7.3, which might account for the problem you are seeing.

-Steven C

**Comment by imtheman69** [comment]
I think your advice re 2.7.3 has worked! Thanks so much,DD
