### ISSUE TITLE
error when running RepEnrich.py

### ISSUE THREAD

**Issue by pingye22** [nerettilab/RepEnrich#5]
Hello,

I used Python-2.7.11. I was able to successfully go through all steps till "Step 4) Run RepEnrich on the data" when errors occur.

My command is:
python RepEnrich.py hg38.fa.out ./repenrichOUT/${ARR[$i-1]} ${ARR[$i-1]} ./RepEnrich ./repenrichOUT/${ARR[$i-1]}_multimap.fastq repenrichOUT/${ARR[$i-1]}_sorted.bam --cpus 24

The error message is:
/bin/sh: module: command not found
Preparing for analysis using RepEnrich...
Conducting region sorting on unique mapping reads....
Traceback (most recent call last):
  File "RepEnrich.py", line 149, in <module>
    if not counts.has_key(str(repeat_key[line[3]])):
KeyError: 'SRR2481145.3765530'

Your help will be greatly appreciated!

**Comment by scriscio** [comment]
Hi,

   We have found that allot of issues are caused by improperly configured setup files.  I recommend downloading the pre-configured setup files for hg38 available here:
[setup](https://drive.google.com/folderview?id=0B1dD8MQRH4qZfmlxOGwtSXRnWDFaVldqbkExdXItZGpySm1mVmhlTVladThHWWhGMmxrLTQ&usp=sharing#list)
repeatmasker file:  hg38_repeatmasker_clean.txt.gz 
setup folder:  RepEnrich_setup_hg38.tar.gz

**Comment by pingye22** [comment]
I got exactly the same error messages when using hg38_repeatmasker_clean.txt.gz and RepEnrich_setup_hg38.tar.gz.

Command:
python RepEnrich.py hg38_repeatmasker_clean.txt ./repenrichOUT/${ARR[$i-1]}t ${ARR[$i-1]} ./RepEnrich_setup_hg38 ./repenrichOUT/${ARR[$i-1]}_multimap.fastq repenrichOUT/${ARR[$i-1]}_sorted.bam --cpus 24

/bin/sh: module: command not found
Preparing for analysis using RepEnrich...
Conducting region sorting on unique mapping reads....
Traceback (most recent call last):
  File "/home/yep/bin/RepEnrich.py", line 149, in <module>
    if not counts.has_key(str(repeat_key[line[3]])):
KeyError: 'SRR2481145.3765530'

**Comment by scriscio** [comment]
Hi,

   If you send me the first 1000 lines of the fastq file used as input for step3 I can try to troubleshoot your error.  Without more information, I can only predict that (1) the issue might be caused by a problem with the command or (2) the fastq file format might be causing an issue.

**Comment by pingye22** [comment]
My step3 Bowtie command:
bowtie genome -p 24 -t -m 1 -v 0 -S --max repenrichOUT/${ARR[$i-1]}_multimap.fastq ${ARR[$i-1]}.fastq repenrichOUT/${ARR[$i-1]}.sam

I used hg38 from UCSC.

The first a few lines of the input SRR2481145.fastq file:
@SRR2481145.1 HISEQ1:392:C5WPKACXX:1:1101:2227:1996 length=50
CTCGTCTCCGCTGTCGCTGTCGCTACTGCTGCTGCAGGGGCCGGATTTCT
+SRR2481145.1 HISEQ1:392:C5WPKACXX:1:1101:2227:1996 length=50
CCCFFFFFHHHHHHJJJJJJJJJIHIJJJJJJFIJJJJJJIJJJBHHFFF
@SRR2481145.2 HISEQ1:392:C5WPKACXX:1:1101:3154:1991 length=50
AGCACATTTATCGTACGTCACAGTGTATGGTGAATATATTATTAAATAAT
+SRR2481145.2 HISEQ1:392:C5WPKACXX:1:1101:3154:1991 length=50
CCCFFFFFHHGHHHIJJIJJJIJHHHGIJIHGGIJJJJJJJJJIIJJJJJ
@SRR2481145.3 HISEQ1:392:C5WPKACXX:1:1101:3377:1978 length=50
CTCGGATTCTACCCTAGCATCACACACCGCACAATCCCCTATCTAGGCCT
+SRR2481145.3 HISEQ1:392:C5WPKACXX:1:1101:3377:1978 length=50
@@@BD1BAFFD?AEF@FBHCHGBAADFHBGGGBHEGHCH>G>FB>FAGCD
@SRR2481145.4 HISEQ1:392:C5WPKACXX:1:1101:5820:1969 length=50
CTGCAATCTCATAAAACTTGAATGGATGAGGAGTTGCTTTTAATGAATGA
+SRR2481145.4 HISEQ1:392:C5WPKACXX:1:1101:5820:1969 length=50
CCCFFFFFHHHHHJJJJJJIIIJJIGJJJJJJJEHIJJJJJJJJJJJJJH
@SRR2481145.5 HISEQ1:392:C5WPKACXX:1:1101:5813:1991 length=50
TGGGAAGCGTGCTCGTGCCCGTATTGCCAAGGGGCTCAGGCTGTGCCGGC
+SRR2481145.5 HISEQ1:392:C5WPKACXX:1:1101:5813:1991 length=50
CCCFFFFFHHHHHGGFHHIIIGHGGGGIIIJGIIJGIJGEGIIJJJGGIG
@SRR2481145.6 HISEQ1:392:C5WPKACXX:1:1101:5858:1996 length=50
GTGGAACTTAGGGGAGTAGTCATGGAAGTCTTTGTAGAAGAGGTGGCATT
+SRR2481145.6 HISEQ1:392:C5WPKACXX:1:1101:5858:1996 length=50
BBBFFFFFHHHHHJIJFHIHJJJJJJJJIJJJJJJJJIJJJJIBGHIJJJ
@SRR2481145.7 HISEQ1:392:C5WPKACXX:1:1101:6115:1971 length=50
CTCGTGGCACTAGCCAGAAATCGTTGCAACTTTGGAACTTCCAAGACAAT
+SRR2481145.7 HISEQ1:392:C5WPKACXX:1:1101:6115:1971 length=50
BCCFDFFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@SRR2481145.8 HISEQ1:392:C5WPKACXX:1:1101:6367:1974 length=50
CTTGACCAAGCGGCCCAACTTGGTGACGGGCATCCACTCCTTATCCTCGG
+SRR2481145.8 HISEQ1:392:C5WPKACXX:1:1101:6367:1974 length=50
CCCFFFFFHHHHHJJJJJJJHJJIIJJJJJIJIJJJJJJJJIJJJJJJJH

The first a few lines of the output SRR2481145_regionsorter.txt (the only output file I got):
chr1    15903   15953   SRR2481145.3765530  255 -   15903   15953   0,0,0   1   50, 0,  50  0.0000000
chr1    15903   15953   SRR2481145.22920333 255 -   15903   15953   0,0,0   1   50, 0,  50  0.0000000
chr1    15910   15960   SRR2481145.28578302 255 +   15910   15960   0,0,0   1   50, 0,  50  0.0000000
chr1    15910   15960   SRR2481145.31556940 255 +   15910   15960   0,0,0   1   50, 0,  50  0.0000000
chr1    15916   15966   SRR2481145.19799802 255 +   15916   15966   0,0,0   1   50, 0,  50  0.0000000
chr1    16062   16112   SRR2481145.12772568 255 -   16062   16112   0,0,0   1   50, 0,  50  0.0000000
chr1    16203   16253   SRR2481145.18752717 255 -   16203   16253   0,0,0   1   50, 0,  50  0.0000000
chr1    16205   16255   SRR2481145.11703702 255 +   16205   16255   0,0,0   1   50, 0,  50  0.0000000

Thanks again!

**Comment by scriscio** [comment]
Hi,

   I could not reproduce your error with the subset of fastq you gave me.  I have a hunch the error might be due to changes in functionality of either the newest versions of samtools or bedtools.  I put the versions I am using in the commented script below run on your example:

```
#Here I load the requirements for RepEnrich 
#This step might be unique to my cluster, however, make sure everything is in $PATH
module load bowtie # I am using bowtie version 1.1.2
module load samtools  # I am using samtools version 1.2
module load bedtools # I am using bedtools v2.17.0

#Make sure you have 8 cpus if not change these variables below:
# in the bowtie command -p 8
# in the RepEnrich command --cpus 8

#I export the location of RepEnrich to path variable.  This allows me to run RepEnrich without specifying
#the full path.  Make sure RepEnrich.py has permission to run as an excecutable.
RepEnrich_path=/gpfs/data/nneretti/scriscio/projects/RepEnrich/RepEnrich/
export PATH=${RepEnrich_path}:$PATH

#I set the path for the annotation as a variable:
annotation_path=/users/nneretti/data/annotation/hg38/

#Next I conduct the alignment step 3. I added the chunkmbs option to allow for increased memory.
#For single-end
#Here I set the problem fq file name
fq1=problem.fastq
#Alignment 
bowtie ${annotation_path}/hg38 -p 8 -t --chunkmbs 512 -m 1 -S --max multimap.fastq $fq1 unique.sam
samtools view -bS unique.sam > unique.bam
samtools sort unique.bam unique_sorted
mv unique_sorted.bam unique.bam
samtools index unique.bam
rm unique.sam

#After the alignment step I run RepEnrich on the output step 4
#For single-end
RepEnrich.py ${annotation_path}hg38_repeatmasker_clean.txt ./testing1 testing1 ${annotation_path}RepEnrich_setup_hg38 \
multimap.fastq unique.bam --cpus 8

```

**Comment by pingye22** [comment]
Thank you for the detailed reply. Your hunch was right: the version of bedtools caused the problem!
Before:
bowtie version 1.1.2
samtools version 1.3.1
bedtools v2.25.0
After:
bowtie version 1.1.2
samtools version 1.3.1
bedtools v2.17.0

I have 3 more questions which I hope you can help with.
QUESTION1
The followings are output from running programs. Are the numbers from Bowtie log and Repenrich log make sense?
Bowtie:
reads processed: 31854509
reads with at least one reported alignment: 19,780,304 (62.10%)
reads that failed to align: 8582523 (26.94%)
reads with alignments suppressed due to -m: 3,491,682 (10.96%)
Repenrich.py:
Conducting region sorting on unique mapping reads....
Identified 1149097unique reads that mapped to repeats.
Processing repeat psuedogenomes...
Sorting and combining the output for both read pairs....
completed ...
Writing and processing intermediate files...
Identified 721712 reads that mapped to repeats for unique and multimappers.

QUESTION2
I have 3 output files with total counts after each file name-
*_fraction_counts.txt: 1,870,539
*_family_fraction_counts.txt: 1,870,809
*_class_fraction_counts.txt: 1,870,809
I noticed 1,870,809 = 1,149,097 + 721,712, the two numbers from Repenrich log.
Why the counts from *_fraction_counts.txt is smaller than the counts from *_family_fraction_counts.txt and *_class_fraction_counts.txt?

QUESTION3
Some class and family names are followed by a question mark (?) in the 3 output files. For example:
Eutr18  LTR?    LTR?    32
hAT?    88.0057748781
SINE?   0.0
DNA?    2785.00113766
LTR?    2303.21542301
What is the meaning of the question mark?

Thanks again!!!
