### ISSUE TITLE
Permission denied for setup?

### ISSUE THREAD

**Issue by dloastormageddon** [nerettilab/RepEnrich#6]
Hi,
I'm new to python and I found that your program seems the best for what I want to do. I'm having trouble setting up the RepEnrich. I'm just trying out the tool with your mm9 dataset for now...
The command I tried is 
python RepEnrich_setup.py /mm9_repeatmasker.txt /mm9.fa /setup_folder_mm9
And I get this result: 
Traceback (most recent call last):
  File "RepEnrich_setup.py", line 51, in <module>
    os.makedirs(setup_folder)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/setup_folder_mm9'

I've installed the dependencies and put them in my PATH. The test files and the RepEnrich py files that I downloaded from the google drive are in ~/Desktop/data (I've already changed directory to this folder before running the command). In the past when this happens with install I usually do (python foo.py install --user) and that gives me permission to write, but this doesn't seem to work with the RepEnrich setup file...?

Thank you for your time and thanks in advance for any help!

T

**Comment by scriscio** [comment]
Hi, 

```
I recommend you manual change the permission of the setup folder.  I am on vacation this week and should be able to assist you better when I return next week.
```

Regards, 

```
Steven
```

-----Original Message-----

**Comment by scriscio** [comment]
This issue is resolved.
