### ISSUE TITLE
--threshold and --tolerance options are never used

### ISSUE THREAD

**Issue by quantumdot** [nerettilab/RepEnrich#8]
Reading though your code, it seems that the options --threshold and --tolerance are never used in any of the computations. The only references to these options in the code is copying their values to local variables. Is this intentional?

**Comment by scriscio** [comment]
Hi,

```
Good Call.   Those variables were used in a very early version of RepEnrich that had a way of intersecting unique reads with repeats that has since been removed.  I removed the unused variables due to your questions.
```

Thank you,
 Steve
