### ISSUE TITLE
Issue of Bowtie or BEDTools not loaded

### ISSUE THREAD

**Issue by dudelaw** [nerettilab/RepEnrich#9]
Hi, thanks for providing this software, but I get an issue of running this software. When I ran RepEnrich, it showed this message.

Error: Bowtie or BEDTools not loaded
Traceback (most recent call last):
  File "/home/username/Desktop/Tools/RepEnrich-master/RepEnrich.py", line 50, in <module>
    subprocess.call(shlex.split("coverageBed -h"), stdout=open(os.devnull, 'wb'), stderr=open(os.devnull, 'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception

Here is the message when I checked coverageBed -h and bowtie --version

Tool:    bedtools coverage (aka coverageBed)
Version: v2.20.1
Summary: Returns the depth and breadth of coverage of features from A 
         on the intervals in B.

Usage:   bedtools coverage [OPTIONS] -a <bed/gff/vcf> -b <bed/gff/vcf>

bowtie version 1.1.2                                                                                                                                         64-bit                                                                                                                                                       Built on lgw01-11                                                                                                                                            Thu Nov 26 11:11:48 UTC 2015
Compiler: gcc version 5.2.1 20151123 (Ubuntu 5.2.1-25ubuntu1)
Options: -O3  -Wl,--hash-style=both -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -Wl,-Bsymbolic-functions -Wl,-z,relro
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

I believe bedtools and bowtie are correctly installed, so I do not know the problem. I appreciate any help and advice.

**Comment by scriscio** [comment]
Hi,

Is bedtools and bowtie in the PATH variable?  You can check what is in the path variable with echo $PATH.  All that step is doing is verifying these two dependencies are in the PATH.  To add them you can do:

working_path=/path/to/script_folder
export PATH=${working_path}:$PATH

Also make sure they have proper execute permissions.

-Steven

**Comment by dudelaw** [comment]
Wow, thanks for your quick reply! I think they are in the PATH variable.

echo $PATH
/home/username/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:~/Desktop/Tools/bedtools2-2.20.1/bin

P.S. bowtie is installed in /usr/bin

**Comment by scriscio** [comment]
Can you try this command exactly as written to see if it raises an exception:

```
coverageBed -h

```

**Comment by dudelaw** [comment]
Tool:    bedtools coverage (aka coverageBed)
Version: v2.20.1
Summary: Returns the depth and breadth of coverage of features from A
     on the intervals in B.

Usage:   bedtools coverage [OPTIONS] -a <bed/gff/vcf> -b <bed/gff/vcf>

Options: 
    -abam   The A input file is in BAM format. Replaces -a.

```
-s  Require same strandedness.  That is, only counts hits in A that
    overlap B on the _same_ strand.
    - By default, overlaps are counted without respect to strand.

-S  Require different strandedness.  That is, only report hits in A
    that overlap B on the _opposite_ strand.
    - By default, overlaps are counted without respect to strand.

-hist   Report a histogram of coverage for each feature in B
    as well as a summary histogram for _all_ features in B.

    Output (tab delimited) after each feature in B:
      1) depth
      2) # bases at depth
      3) size of B
      4) % of B at depth

-d  Report the depth at each position in each B feature.
    Positions reported are one based.  Each position
    and depth follow the complete B feature.

-counts Only report the count of overlaps, don't compute fraction, etc.

-split  Treat "split" BAM or BED12 entries as distinct BED intervals.
    when computing coverage.
    For BAM files, this uses the CIGAR "N" and "D" operations 
    to infer the blocks for computing coverage.
    For BED12 files, this uses the BlockCount, BlockStarts,
    and BlockEnds fields (i.e., columns 10,11,12).
```

Default Output:  
     After each entry in B, reports: 
       1) The number of features in A that overlapped the B interval.
       2) The number of bases in B that had non-zero coverage.
       3) The length of the entry in B.
       4) The fraction of bases in B that had non-zero coverage.

**Comment by scriscio** [comment]
Hi,

   That is really strange.  For some reason the python script is not seeing coverageBed in PATH. You can verify this is true by opening python from the command prompt and running:

```
import shlex
import subprocess
try:
     subprocess.call(shlex.split("coverageBed -h"), stdout=open(os.devnull, 'wb'), stderr=open(os.devnull, 'wb'))
except OSError:
     print "Error: Bowtie or BEDTools not loaded"
```

This might be an issue with how python and the subprocess module are interacting with your system.

-Steven

**Comment by dudelaw** [comment]
This is how it looks like when I typed the command.

> > > import shlex
> > > import subprocess
> > > try:
> > > ...      subprocess.call(shlex.split("coverageBed -h"), stdout=open(os.devnull, 'wb'), stderr=open(os.devnull, 'wb'))
> > > ...  except OSError:
> > >   File "<stdin>", line 3
> > >     except OSError:
> > >                   ^
> > > IndentationError: unindent does not match any outer indentation level
> > >      print "Error: Bowtie or BEDTools not loaded"
> > >   File "<stdin>", line 1
> > >     print "Error: Bowtie or BEDTools not loaded"
> > >     ^
> > > IndentationError: unexpected indent

**Comment by scriscio** [comment]
Hi try it a again, there was a single space before except that caused an indentation error.

**Comment by dudelaw** [comment]
Sorry for the mistake. Here is the new one.
try:
...     subprocess.call(shlex.split("coverageBed -h"), stdout=open(os.devnull, 'wb'), stderr=open(os.devnull, 'wb'))
... except OSError:
...     print "Error: Bowtie or BEDTools not loaded"
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'os' is not defined

**Comment by dudelaw** [comment]
Sorry for the mistake since I am quite new to bioinformatics. Here is the new one.
import shlex
import subprocess
try:
...     subprocess.call(shlex.split("coverageBed -h"), stdout=open(os.devnull, 'wb'), stderr=open(os.devnull, 'wb'))
... except OSError:
...     print "Error: Bowtie or BEDTools not loaded"
...     
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'os' is not defined

**Comment by dudelaw** [comment]
Here is the new one.
import os
import shlex
import subprocess
try:
...     subprocess.call(shlex.split("coverageBed -h"), stdout=open(os.devnull, 'wb'), stderr=open(os.devnull, 'wb'))
... except OSError:
...     print "Error: Bowtie or BEDTools not loaded"
... 
Error: Bowtie or BEDTools not loaded

subprocess.call(shlex.split("coverageBed -h"), stdout=open(os.devnull, 'wb'), stderr=open(os.devnull, 'wb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by scriscio** [comment]
Hi,

What this short piece of code verified is that python for some reason is not communicating with the $PATH variable properly.  This likely indicates an issue with python on your system.  I am aware of this issue occurring on some Windows systems.  I have not seen this issue for Ubuntu though.  One last thing to try is to add the coverageBed to path (e.g. for /gpfs/runtime/bib/install/bedtools/2.20.1/bin/coverageBed) :

  working_path=/gpfs/runtime/bib/install/bedtools/2.20.1/bin
  export PATH=${working_path}:$PATH

**Comment by dudelaw** [comment]
Thanks for your help. Finally, I solved it by simply install the bedtools to /use/local/bin which can be recognized in PATH variable. However, I dunno the reason why previous method did not work.

**Comment by scriscio** [comment]
Hi,

   I am glad you were able to resolve the issue.
